// All settings and internal/debug routes in one chunk, so moving between them after the first
// load is instant instead of a fresh suspend per route.
export { default as AboutSettingsScreen } from '@web/modules/settings/screens/AboutSettingsScreen'
export { default as AccountsSettingsScreen } from '@web/modules/settings/screens/AccountsSettingsScreen'
export { default as AddressBookSettingsScreen } from '@web/modules/settings/screens/AddressBookSettingsScreen'
export { default as DevicePasswordChangeSettingsScreen } from '@web/modules/settings/screens/DevicePasswordChangeSettingsScreen'
export { default as DevicePasswordRecoverySettingsScreen } from '@web/modules/settings/screens/DevicePasswordRecoverySettingsScreen'
export { default as DevicePasswordSetSettingsScreen } from '@web/modules/settings/screens/DevicePasswordSetSettingsScreen'
export { default as GeneralSettingsScreen } from '@web/modules/settings/screens/GeneralSettingsScreen'
export { default as InternalLogsScreen } from '@web/modules/debug/screens/InternalLogsScreen'
export { default as ManageTokensSettingsScreen } from '@web/modules/settings/screens/ManageTokensSettingsScreen'
export { default as NetworksConfiguration } from '@web/modules/network-settings/screens'
export { default as NetworksSettingsScreen } from '@web/modules/settings/screens/NetworksSettingsScreen'
export { default as OptOutsScreen } from '@web/modules/settings/screens/OptOutsScreen'
export { default as PrivacyOptOutsConfiguration } from '@web/modules/network-settings/screens/PrivacyOptOutsConfiguration'
export { default as RecoveryPhrasesSettingsScreen } from '@web/modules/settings/screens/RecoveryPhrasesSettingsScreen'
export { default as SignedMessageHistorySettingsScreen } from '@web/modules/settings/screens/SignedMessageHistorySettingsScreen'
export { default as TermsSettingsScreen } from '@web/modules/settings/screens/TermsSettingsScreen'
export { default as TransactionHistorySettingsScreen } from '@web/modules/settings/screens/TransactionHistorySettingsScreen'
