import Fuse from 'fuse.js'
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useForm } from 'react-hook-form'
import { useTranslation } from 'react-i18next'
import { Linking, Platform, View } from 'react-native'
import { useModalize } from 'react-native-modalize'
import { WebView, WebViewNavigation } from 'react-native-webview'
import { useLocation } from 'react-router-native'

import { Dapp } from '@ambire-common/interfaces/dapp'
import { getDappIdFromUrl } from '@ambire-common/libs/dapps/helpers'
import { isValidHostname, isValidURL } from '@ambire-common/services/validations'
import AmbireBrandLogo from '@common/assets/svg/AmbireBrandLogo'
import AmbireLogo from '@common/assets/svg/AmbireLogo'
import AmbireLogoWithBackgroundAndLogotype from '@common/assets/svg/AmbireLogoWithBackgroundAndLogotype'
import GlobeIcon from '@common/assets/svg/GlobeIcon'
import GoogleIcon from '@common/assets/svg/GoogleIcon'
import Banner from '@common/components/Banner'
import BottomSheet from '@common/components/BottomSheet'
import Search from '@common/components/Search'
import Text from '@common/components/Text'
import { ControllersMiddlewareContext } from '@common/contexts/controllersMiddlewareContext'
import useController from '@common/hooks/useController'
import useDebounce from '@common/hooks/useDebounce'
import { AnimatedPressable } from '@common/hooks/useHover'
import useTheme from '@common/hooks/useTheme'
import DappItem from '@common/modules/explore/components/DappItem'
import eventBus from '@common/services/event/eventBus'
import spacings from '@common/styles/spacings'
import flexbox from '@common/styles/utils/flexbox'
import { WEBVIEW_DEV_HOST } from '@env'
import { MobileLayoutContainer } from '@mobile/components/MobileLayoutWrapper'
import DappProgressBar from '@mobile/modules/webview/components/DappProgressBar'
import DappWebViewFooter from '@mobile/modules/webview/components/DappWebViewFooter'

// SECURITY: Generate a 256-bit random token used to gate the RN <-> WebView bridge.
// Cross-origin iframes cannot read main-frame globals (Same-Origin Policy), so they
// cannot forge messages with a valid token. Called once per WebView mount.
const generateBridgeToken = () => {
  const bytes = new Array(32)
  for (let i = 0; i < 32; i++) {
    bytes[i] = Math.floor(Math.random() * 256)
  }
  return bytes.map((b) => b.toString(16).padStart(2, '0')).join('')
}

// The provider bundle is generated by webpack.webview.config.js
// @ts-ignore
const ambireInpageBundle = require('../../services/ambire-inpage-bundle.json')
// @ts-ignore
const ethereumInpageBundle = require('../../services/ethereum-inpage-bundle.json')

// Some dapps (e.g. chainlist) gate their "Connect Wallet" UI on a mobile
// User-Agent and never call the injected provider, even though window.ethereum
// is present. Presenting a desktop UA makes them offer the injected wallet path.
const DESKTOP_USER_AGENT =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15'

// SECURITY: Stash native references before any page JS can overwrite them.
// injectJavaScript (used for responses/broadcasts) runs AFTER page JS, so
// downstream injections must reach these pre-captured refs rather than the
// (potentially overwritten) globals like window.postMessage or window.dispatchEvent.
// Stored on a non-enumerable, non-configurable, frozen descriptor so the
// page cannot delete or reassign the stash itself.
const jsNativeStash = `
  (function() {
    var stash = Object.freeze({
      postMessage: window.postMessage.bind(window),
      dispatchEvent: window.dispatchEvent.bind(window)
    });
    Object.defineProperty(window, '__ambireNative', {
      value: stash,
      writable: false,
      configurable: false,
      enumerable: false
    });
  })();
`

// Dev-only WebView helpers
const devOnlyHelpers = `
  // Forward console output to React Native for easy debugging
  (function() {
    var originalLog = console.log;
    var originalWarn = console.warn;
    var originalError = console.error;

    // Expand objects that JSON.stringify can't see: Events (esp. CloseEvent / WebSocket
    // error events) and Errors. Without this, the webpack-dev-server HMR client surfaces
    // ws errors as the useless "{\\"isTrusted\\":true}" because Event props are getters,
    // not own enumerable keys.
    function describeArg(arg) {
      if (arg === null) return 'null';
      if (arg === undefined) return 'undefined';
      if (typeof arg !== 'object') return String(arg);

      if (arg instanceof Error) {
        return JSON.stringify({
          __type: arg.name || 'Error',
          message: arg.message,
          stack: arg.stack
        });
      }

      // CloseEvent (extends Event) — what the WebSocket fires on disconnect.
      if (typeof CloseEvent !== 'undefined' && arg instanceof CloseEvent) {
        var t = arg.target || {};
        return JSON.stringify({
          __type: 'CloseEvent',
          type: arg.type,
          code: arg.code,
          reason: arg.reason,
          wasClean: arg.wasClean,
          targetUrl: t.url,
          targetReadyState: t.readyState
        });
      }

      // Generic Event (e.g. WebSocket 'error' event — code/reason not available).
      if (typeof Event !== 'undefined' && arg instanceof Event) {
        var et = arg.target || {};
        return JSON.stringify({
          __type: arg.constructor && arg.constructor.name || 'Event',
          type: arg.type,
          targetUrl: et.url,
          targetReadyState: et.readyState,
          isTrusted: arg.isTrusted
        });
      }

      try {
        return JSON.stringify(arg);
      } catch(e) {
        return String(arg);
      }
    }

    function sendToRN(type, args) {
      window.ReactNativeWebView.postMessage(JSON.stringify({
        type: 'log',
        logType: type,
        args: Array.from(args).map(describeArg)
      }));
    }

    console.log = function() {
      sendToRN('log', arguments);
      originalLog.apply(console, arguments);
    };
    console.warn = function() {
      sendToRN('warn', arguments);
      originalWarn.apply(console, arguments);
    };
    console.error = function() {
      sendToRN('error', arguments);
      originalError.apply(console, arguments);
    };
  })();

  // Surface uncaught page errors via the same pipe
  window.onerror = function(msg, url, lineNo, columnNo, error) {
    var errStr = error ? (error.stack || error.message || String(error)) : msg;
    console.error('[Ambire window.onerror]', errStr, 'at', url, ':', lineNo, ':', columnNo);
    return false;
  };

  // Surface unhandled promise rejections — webpack-dev-server fetch failures often
  // land here instead of window.onerror.
  window.addEventListener('unhandledrejection', function(ev) {
    var reason = ev && ev.reason;
    var detail = reason instanceof Error
      ? (reason.stack || reason.message || String(reason))
      : (function() { try { return JSON.stringify(reason); } catch(e) { return String(reason); } })();
    console.error('[Ambire unhandledrejection]', detail);
  });

  // Hide dev error overlays (react-error-overlay, webpack-dev-server, Next.js dev)
  // The document may not be fully loaded

  document.addEventListener('DOMContentLoaded', function() {
    var s = document.createElement('style');
    s.textContent = '#__react-error-overlay__,iframe#webpack-dev-server-client-overlay,nextjs-portal{display:none!important}';
    (document.head || document.documentElement).appendChild(s);
  });
`

// Comma-locale keypads type "," as the decimal separator. Rewrite it to "."
// in numeric dapp inputs (React-safe: native setter + bubbled input event).
const decimalSeparatorFix = `
  (function() {
    document.addEventListener('input', function(e) {
      var el = e.target;
      if (!el || el.tagName !== 'INPUT') return;
      var inputMode = (el.getAttribute('inputmode') || '').toLowerCase();
      var type = (el.type || '').toLowerCase();
      var isNumeric = inputMode === 'decimal' || inputMode === 'numeric' || type === 'number';
      if (!isNumeric) return;
      if (el.value.indexOf(',') === -1) return;
      var normalized = el.value.split(',').join('.');
      var setter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value').set;
      setter.call(el, normalized);
      el.dispatchEvent(new Event('input', { bubbles: true }));
    }, true);
  })();
`

const WEBVIEW_DEV_SERVER_PORT = 8182
const getDevServerUrl = () => {
  if (Platform.OS === 'android') {
    return `http://${WEBVIEW_DEV_HOST || '10.0.2.2'}:${WEBVIEW_DEV_SERVER_PORT}`
  }
  return `http://localhost:${WEBVIEW_DEV_SERVER_PORT}`
}

const DappWebViewScreen = () => {
  const [devAmbireCode, setDevAmbireCode] = useState<string | null>(null)
  const [devEthereumCode, setDevEthereumCode] = useState<string | null>(null)

  useEffect(() => {
    if (__DEV__) {
      Promise.all([
        fetch(`${getDevServerUrl()}/ambire-inpage-bundle.js`).then((res) => res.text()),
        fetch(`${getDevServerUrl()}/ethereum-inpage-bundle.js`).then((res) => res.text())
      ])
        .then(([ambireCode, ethereumCode]) => {
          setDevAmbireCode(ambireCode)
          setDevEthereumCode(ethereumCode)
        })
        .catch((err) => {
          console.warn('[Ambire] Failed to fetch inpage bundles from dev server', err)
        })
    }
  }, [])

  const { theme } = useTheme()
  const { t } = useTranslation()
  const location = useLocation()
  const { dispatch } = React.useContext(ControllersMiddlewareContext)
  const {
    state: { dapps },
    currentDapp,
    setDappUrl,
    dispatch: dappsDispatch
  } = useController('DappsController')

  const {
    state: { visibleUserRequests, currentUserRequest }
  } = useController('RequestsController')

  // Initial State from Route
  const initialUrl = (location.state as any)?.url || 'https://google.com'
  // When opened to view a single URL (e.g. a DeFi position), the footer renders
  // a back arrow instead of the home icon so the user returns to the previous screen.
  const showBackButton = !!(location.state as any)?.showBackButton

  useEffect(() => {
    // Record the visited dapp into Recents. addToRecentDapps no-ops when the URL
    // doesn't resolve to a catalog dapp, so direct-URL / Google searches are safe.
    try {
      const id = getDappIdFromUrl(initialUrl)
      dappsDispatch({
        type: 'method',
        params: { method: 'addToRecentDapps', args: [id] }
      })
    } catch {
      // ignore malformed URLs
    }
    // Only run on mount with the initial URL.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // WebView Refs & State
  const webviewRef = useRef<WebView>(null)
  const [currentUrl, setCurrentUrl] = useState<string>(initialUrl)
  const currentUrlRef = useRef<string>(initialUrl)
  // SECURITY: bridge token generated ONCE per WebView mount. NEVER rotated -
  // the token must stay identical between the injected script (JS side) and the
  // React verification (RN side). Lazy useState initializer guarantees stability.
  const [bridgeToken] = useState<string>(() => generateBridgeToken())
  // Tracks the URL of the last successful `onLoadEnd(!loading)` event. Used
  // on Android to decide whether a subsequent `onLoadStart` is a fresh
  // top-level navigation (reset the bar) or a same-origin SPA/hash
  // navigation that should be ignored. Matches `webviewState.resolvedUrl`
  // in Rabby's `useWebViewControl` hook.
  const resolvedUrlRef = useRef<string>('')
  const [progress, setProgress] = useState(0)
  const [isLoading, setIsLoading] = useState(true)
  const [canGoBack, setCanGoBack] = useState(false)
  // Drives WebView source; set at mount + only by user address-bar nav. Never
  // from nav callbacks, else source.uri re-feeds → RNW reloads → snaps back.
  const [sourceUri, setSourceUri] = useState<string>(initialUrl)

  // Atomic setter used by every WebView load callback so `progress` and
  // `isLoading` always stay in sync. Mirrors Rabby's `updateProgressState`.
  const updateProgressState = useCallback((next: { progress: number; isLoading: boolean }) => {
    setProgress(next.progress)
    setIsLoading(next.isLoading)
  }, [])

  // Load the nav-state URL on mount and when a new dapp opens in the mounted
  // browser. Keyed on initialUrl only so in-dapp nav can't retrigger a reload.
  useEffect(() => {
    setSourceUri(initialUrl)
    setDappUrl?.(initialUrl)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialUrl])

  // Bottom Sheet & Search Form State
  const { ref: searchModalRef, open: openSearchModal, close: closeSearchModal } = useModalize()
  const { control: headerControl, setValue: setHeaderValue } = useForm({
    defaultValues: { search: initialUrl }
  })
  const {
    control: searchControl,
    watch: searchWatch,
    setValue: setSearchValue
  } = useForm({ defaultValues: { search: '' } })
  const bottomSheetSearchQuery = searchWatch('search')
  const debouncedSearch = useDebounce({ value: bottomSheetSearchQuery, delay: 350 })

  const searchHeaderComponent = useMemo(
    () => (
      <Search
        control={searchControl}
        placeholder={t('Search or enter URL')}
        autoFocus={true}
        containerStyle={spacings.mbLg}
      />
    ),
    [searchControl, t]
  )

  const { account } = useController('SelectedAccountController').state

  const smartAccountType = useMemo(() => {
    if (account?.creation) return 'Ambire'
    if (account?.safeCreation) return 'Safe'
    return undefined
  }, [account])

  const handleOpenSearchModal = useCallback(() => {
    setSearchValue('search', currentUrl)
    openSearchModal()
  }, [openSearchModal, setSearchValue, currentUrl])

  const handleGoBack = useCallback(() => {
    webviewRef.current?.goBack()
  }, [])

  const handleRefresh = useCallback(() => {
    webviewRef.current?.reload()
  }, [])

  const hostname = useMemo(() => {
    try {
      return new URL(currentUrl).hostname
    } catch {
      return currentUrl
    }
  }, [currentUrl])

  // Keep the Header placeholder in sync with current URL
  useEffect(() => {
    setHeaderValue('search', hostname)
  }, [hostname, setHeaderValue])

  const handleShouldStartLoadWithRequest = useCallback(
    (event: { url: string; navigationType: string }) => {
      const { url } = event
      try {
        const parsed = new URL(url)
        const protocol = parsed.protocol.replace(':', '')

        // Allow HTTPS and about: (blank pages, error pages).
        // Also allow blob: — chart/visualization libraries (and the web workers
        // they spawn) commonly render via blob: URLs, so blocking it leaves the
        // chart area blank even though the rest of the page loads fine.
        if (protocol === 'https' || protocol === 'about' || protocol === 'blob') {
          return true
        }

        // Hand off wallet deep links to the OS
        // Note: wc protocol is now intercepted by WalletConnectProvider, but we still openURL
        // to trigger the Linking event within the app.
        if (protocol === 'wc' || protocol === 'metamask' || protocol === 'ethereum') {
          console.log('[DappWebView] Handing off wallet deep link to OS:', url)
          Linking.openURL(url).catch((err) => {
            console.warn('[DappWebView] Failed to open wallet deep link:', err)
          })
          return false
        }

        // Block suspicious protocols that could be used maliciously
        if (
          protocol === 'tel' ||
          protocol === 'mailto' ||
          protocol === 'javascript' ||
          protocol === 'data'
        ) {
          console.warn('[DappWebView] Blocked suspicious protocol:', protocol, url)
          return false
        }

        // For any other unknown protocol, block by default for security
        console.warn('[DappWebView] Blocked unknown protocol:', protocol, url)
        return false
      } catch {
        // If URL parsing fails, allow it (could be a relative URL or special scheme)
        return true
      }
    },
    []
  )

  const updateCurrentOriginRef = useCallback(
    (nextUrl: string) => {
      if (!nextUrl || nextUrl === currentUrlRef.current) return
      // Only track HTTPS URLs. `onShouldStartLoadWithRequest` already blocks
      // non-HTTPS navigations, so this is defense-in-depth: never let the ref
      // drift to an unsafe scheme (about:blank intermediate states, etc.).
      try {
        if (new URL(nextUrl).protocol !== 'https:') return
      } catch {
        return
      }
      const previousUrl = currentUrlRef.current
      currentUrlRef.current = nextUrl
      try {
        if (new URL(previousUrl).origin !== new URL(nextUrl).origin) {
          dispatch({ type: 'WEBVIEW_ORIGIN_CHANGED', params: { previousOrigin: previousUrl } })
        }
      } catch {
        // previousUrl may not be a valid URL yet (e.g. on first load)
      }
    },
    [dispatch]
  )

  const handleNavigationStateChange = useCallback(
    (e: WebViewNavigation) => {
      setCanGoBack(e.canGoBack)

      if (e.loading) return

      try {
        const url = new URL(e.url)
        if (url.protocol !== 'https:') {
          console.warn('[DappWebView] Blocked navigation to non-HTTPS URL:', e.url)
          return
        }
        updateCurrentOriginRef(e.url)
        setCurrentUrl(e.url)
        // Keep dappUrl in sync with the actual page the WebView is on so that
        // currentDapp (and the ManageApp bottom sheet) always reflect the real URL.
        // setDappUrl is called eagerly here AND in handleLoadStart; the helper
        // deduplicates same-URL calls so there is no double-fetch.
        setDappUrl?.(e.url)
      } catch {
        console.warn('[DappWebView] Invalid URL in navigation:', e.url)
      }
    },
    [updateCurrentOriginRef, setDappUrl]
  )

  // This MUST be the first script injected. It hardens the RN <-> WebView bridge by:
  // 1. Wrapping window.ReactNativeWebView.postMessage to inject a per-mount token.
  // 2. Wrapping window.webkit.messageHandlers.ReactNativeWebView.postMessage on iOS
  //    so iframes calling the WK API directly cannot bypass the wrap (iOS only).
  // 3. Keeping the legacy origin check as defense-in-depth.
  //
  // The token is the primary defense - cross-origin iframes can't read main-frame
  // globals, so any iframe call to the bridge will lack the token and be rejected
  // on the RN side in handleMessage.
  //
  // useMemo with [bridgeToken] dep guarantees the script always reflects the same
  // token used by the React verification (bridgeToken never changes after mount).
  const jsBridgeHarden = useMemo(
    () => `
    (function() {
      var AMBIRE_TOKEN = ${JSON.stringify(bridgeToken)};
      var pageOrigin = window.location.origin;

      function safeStartsWith(str, search) {
        if (typeof str !== 'string' || typeof search !== 'string') return false;
        for (var i = 0; i < search.length; i++) {
          if (str[i] !== search[i]) return false;
        }
        return true;
      }

      function addTokenAndValidate(msg) {
        try {
          var json = JSON.parse(msg);
          // Defense-in-depth: legacy origin check based on payload.origin
          if (json && json.payload && json.payload.origin) {
            var msgOrigin = json.payload.origin;
            if (!(pageOrigin === msgOrigin ||
                  pageOrigin === msgOrigin + '/' ||
                  safeStartsWith(msgOrigin, pageOrigin + '/'))) {
              console.warn('[Ambire JSBridgeHarden] Origin mismatch: expected ' + pageOrigin + ', got ' + msgOrigin);
              return null;
            }
          }
          // Primary defense: stamp the token so RN can verify the message came
          // from the main frame's wrapped bridge (cross-origin iframes can't read it).
          json.__ambireToken = AMBIRE_TOKEN;
          return JSON.stringify(json);
        } catch (e) {
          // Non-JSON message - pass through unchanged. RN will reject if it lacks token.
          return msg;
        }
      }

      // 1. Wrap window.ReactNativeWebView.postMessage (Android primary, iOS shim)
      if (window.ReactNativeWebView) {
        try {
          var originalPostMessage = window.ReactNativeWebView.postMessage.bind(window.ReactNativeWebView);
          function wrappedPostMessage(msg) {
            var stamped = addTokenAndValidate(msg);
            if (stamped === null) return; // origin check rejected
            return originalPostMessage(stamped);
          }
          window.ReactNativeWebView = new Proxy(window.ReactNativeWebView, {
            get: function(target, prop) {
              if (prop === 'postMessage') return wrappedPostMessage;
              var val = target[prop];
              return typeof val === 'function' ? val.bind(target) : val;
            }
          });
        } catch (e) {
          console.error('[Ambire JSBridgeHarden] Failed to wrap ReactNativeWebView:', e);
        }
      }

      // 2. Wrap iOS WK API. On iOS, react-native-webview's window.ReactNativeWebView.postMessage
      // is a thin shim over window.webkit.messageHandlers.ReactNativeWebView.postMessage.
      // Cross-origin iframes get their own window.webkit.messageHandlers in iOS, so wrapping
      // here only affects the main frame - which is the goal: iframe calls go through
      // their own un-wrapped WK API and arrive at RN without the token.
      if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.ReactNativeWebView) {
        try {
          var wkHandler = window.webkit.messageHandlers.ReactNativeWebView;
          var originalWKPostMessage = wkHandler.postMessage.bind(wkHandler);
          // Use a plain assignment (not Object.defineProperty with configurable:false) so
          // we don't break legitimate code that may need to introspect/replace handlers.
          wkHandler.postMessage = function(msg) {
            var stamped = addTokenAndValidate(msg);
            if (stamped === null) return; // origin check rejected
            return originalWKPostMessage(stamped);
          };
        } catch (e) {
          console.error('[Ambire JSBridgeHarden] Failed to wrap WK API:', e);
        }
      }
    })();
  `,
    [bridgeToken]
  )

  // ── Inpage Provider Injection ──
  const injectionScript = useMemo(() => {
    // Use the dynamically fetched dev code if available, fallback to bundled code
    const baseCodeAmbire = (__DEV__ && devAmbireCode) || ambireInpageBundle.code
    const baseCodeEthereum = (__DEV__ && devEthereumCode) || ethereumInpageBundle.code

    return `
    try {
      ${jsNativeStash}

      ${jsBridgeHarden}

      ${decimalSeparatorFix}

      ${__DEV__ ? devOnlyHelpers : ''}

      window.addEventListener('message', function(event) {
        // SECURITY: Only forward messages originating from the main frame itself.
        // A cross-origin iframe can call window.parent.postMessage({ topic: 'ambireProviderRequest', ... }, '*')
        // which would otherwise be relayed to the RN bridge and stamped with a valid token by the
        // main-frame-wrapped window.ReactNativeWebView proxy, bypassing the hardening.
        // Mirrors the check in the extension's windowMessenger (web/extension-services/messengers/internal/window.ts).
        if (event.source !== window) return;

        ${
          // Debug-only: dapps poll the provider continuously, so logging (and
          // especially JSON.stringify-ing) every window message floods the RN
          // bridge and heats the device. Keep it out of production builds.
          __DEV__
            ? "console.log('[Ambire] [Bridge DEBUG] window message received:', typeof event.data === 'string' ? event.data : JSON.stringify(event.data));"
            : ''
        }

        if (event.data && typeof event.data.topic === 'string' && (event.data.topic.indexOf('ambireProviderRequest') > -1 || event.data.topic.indexOf('ambireNextBuildProviderRequest') > -1)) {
          if (event.data.topic.indexOf('<') === 0) {
            // Ignore response messages sent from RN back to the injected provider.
            return;
          }
          ${
            __DEV__
              ? "console.log('[Ambire] [Bridge] Caught MATCHING message:', event.data.topic, event.data.payload ? event.data.payload.method : 'no-payload');"
              : ''
          }
          if (window.ReactNativeWebView) {
            window.ReactNativeWebView.postMessage(JSON.stringify({
              type: 'providerRequest',
              payload: event.data.payload,
              id: event.data.id,
              topic: event.data.topic
            }));
          } else {
            console.error('[Ambire] [Bridge] window.ReactNativeWebView NOT FOUND');
          }
        }
      });

      (function() {
        try {
        ${__DEV__ ? "console.log('[Ambire] injecting provider code');" : ''}
          ${baseCodeAmbire}
          ${baseCodeEthereum}
          ${__DEV__ ? "console.log('[Ambire] Provider code executed successfully');" : ''}
        } catch(e) {
          console.error('[Ambire] Provider code CRASHED:', e && e.stack ? e.stack : (e && e.message ? e.message : String(e)));
        }

        ${
          __DEV__
            ? "console.log('[Ambire] window.ethereum:', !!window.ethereum, 'window.ambire:', !!window.ambire);"
            : ''
        }
      })();
      true;
    } catch (e) {
      console.error('[Ambire] Failed to inject provider code:', e && e.stack ? e.stack : (e && e.message ? e.message : String(e)));
    }
    `
  }, [devAmbireCode, devEthereumCode, jsBridgeHarden])

  // Dapp Search Data Filtering
  const searchableDapps = useMemo(
    () =>
      dapps.map((dapp: Dapp) => ({
        dapp,
        name: dapp.name.toLowerCase(),
        url: dapp.url.toLowerCase(),
        description: dapp.description?.toLowerCase() || ''
      })),
    [dapps]
  )

  const searchResults = useMemo(() => {
    if (!debouncedSearch) return []
    const fuse = new Fuse(searchableDapps, {
      keys: [
        { name: 'name', weight: 0.7 },
        { name: 'url', weight: 0.2 },
        { name: 'description', weight: 0.1 }
      ],
      shouldSort: false,
      threshold: 0.2, // matching ExploreScreen logic
      minMatchCharLength: 1
    })
    const results = fuse.search(debouncedSearch)
    return results.map((result) => result.item.dapp)
  }, [debouncedSearch, searchableDapps])

  // Data to render in bottom sheet list
  const listData = useMemo(() => {
    const data: any[] = []
    if (debouncedSearch) {
      data.push({ type: 'googleSearch', query: debouncedSearch })
      if (isValidURL(debouncedSearch) || isValidHostname(debouncedSearch)) {
        data.push({ type: 'openPage', query: debouncedSearch })
      }
    } else {
      const suggestedDapps = dapps.filter((dapp: Dapp) => dapp.favorite || dapp.isConnected)
      const emptySearchFallback = suggestedDapps.length > 0 ? suggestedDapps : dapps
      data.push(...emptySearchFallback.map((dapp: Dapp) => ({ type: 'dapp', dapp })))
    }
    data.push(...searchResults.map((dapp: Dapp) => ({ type: 'dapp', dapp })))
    return data
  }, [debouncedSearch, searchResults, dapps])

  const handleNavigateToUrl = useCallback(
    (url: string) => {
      setSourceUri(url)
      setDappUrl?.(url)
      closeSearchModal()
    },
    [closeSearchModal, setDappUrl]
  )

  const renderSearchItem = useCallback(
    ({ item }: { item: any }) => {
      if (item.type === 'openPage') {
        const url = isValidURL(item.query) ? item.query : `https://${item.query}`
        return (
          <AnimatedPressable
            onPress={() => handleNavigateToUrl(url)}
            style={[flexbox.directionRow, flexbox.alignCenter, spacings.mb]}
          >
            <View
              style={[
                spacings.mrSm,
                flexbox.center,
                {
                  backgroundColor: theme.secondaryBackground,
                  borderRadius: 50,
                  width: 40,
                  height: 40
                }
              ]}
            >
              <GlobeIcon />
            </View>
            <Text weight="medium" appearance="secondaryText">
              Open "{item.query}"
            </Text>
          </AnimatedPressable>
        )
      }

      if (item.type === 'googleSearch') {
        return (
          <AnimatedPressable
            onPress={() =>
              handleNavigateToUrl(
                `https://www.google.com/search?q=${encodeURIComponent(item.query)}`
              )
            }
            style={[flexbox.directionRow, flexbox.alignCenter, spacings.mb]}
          >
            <View
              style={[
                spacings.mrSm,
                flexbox.center,
                {
                  backgroundColor: theme.secondaryBackground,
                  borderRadius: 50,
                  width: 40,
                  height: 40
                }
              ]}
            >
              <GoogleIcon />
            </View>
            <Text weight="medium" appearance="secondaryText">
              Search Google for "{item.query}"
            </Text>
          </AnimatedPressable>
        )
      }

      if (item.type === 'dapp') {
        return (
          <DappItem {...item.dapp} onPressOverride={() => handleNavigateToUrl(item.dapp.url)} />
        )
      }
      return null
    },
    [theme, handleNavigateToUrl]
  )

  const searchKeyExtractor = useCallback(
    (item: any, index: number) => (item.type === 'dapp' ? item.dapp.url : `google-${index}`),
    []
  )

  const searchFlatListProps = useMemo(
    () => ({
      contentContainerStyle: spacings.pbLg,
      data: listData,
      renderItem: renderSearchItem,
      keyExtractor: searchKeyExtractor,
      keyboardShouldPersistTaps: 'handled' as const
    }),
    [listData, renderSearchItem, searchKeyExtractor]
  )

  const handleMessage = useCallback(
    (event: any) => {
      try {
        const data = JSON.parse(event.nativeEvent.data)
        if (__DEV__) {
          console.log(
            '[DappWebView] RN received message type:',
            data.type || (data.method ? 'raw-provider-request' : 'unknown')
          )
        }
        if (data.type === 'log') {
          const prefix = `[WebView ${data.logType}]`

          console.log(prefix, ...data.args)
        } else if (data.type === 'providerRequest' || (data.method && data.id)) {
          const method = data.type === 'providerRequest' ? data.payload?.method : data.method
          if (__DEV__) console.log('[DappWebView] Received providerRequest:', method, data.id)

          // SECURITY: Verify the bridge token. The token is injected only into the
          // main frame, so cross-origin iframes cannot forge messages with it.
          // This is the primary defense against iframe origin spoofing.
          if (data.__ambireToken !== bridgeToken) {
            console.warn(
              '[DappWebView] Bridge token mismatch - rejecting provider request.',
              'Method:',
              method,
              'This typically indicates an iframe attempting to bypass the bridge.'
            )
            return
          }

          const payload =
            data.type === 'providerRequest'
              ? data.payload
              : { method: data.method, params: data.params }
          const topic = data.topic || '> ambireProviderRequest'

          // Derive current origin from the trusted source (WebView's URL).
          // payload.origin is self-reported by the page and is NOT trusted -
          // it gets overridden below with currentUrlRef.current before dispatch.
          // Iframe spoofing is prevented by the bridge token check above.
          const currentOrigin = (() => {
            try {
              return new URL(currentUrlRef.current).origin
            } catch {
              return null
            }
          })()

          // SECURITY: Always store the expected origin for EVERY request id.
          // The response gate compares this against currentUrlRef.current at
          // response time to detect navigation during async operations.
          if (data.id) {
            requestOriginsRef.current[data.id] = currentOrigin || ''
          }

          dispatch({
            type: 'HANDLE_PROVIDER_REQUEST',
            params: {
              request: { ...payload, origin: currentUrlRef.current },
              requestId: data.id,
              providerId: 1,
              topic,
              tabId: 1
            }
          })
        }
      } catch (e) {
        // Ignore non-JSON or other messages
      }
    },
    [dispatch, bridgeToken]
  )

  // Track the URL at the time of each request to detect navigation during async operations
  const requestOriginsRef = useRef<Record<string, string>>({})

  useEffect(() => {
    const onProviderResponse = (data: any) => {
      if (__DEV__) {
        console.log(
          '[DappWebView] Sending response back to WebView:',
          data.requestId,
          data.result ? 'SUCCESS' : 'ERROR/NULL'
        )
      }

      // SECURITY: Look up the expected origin recorded when the request was received.
      const expectedOrigin = requestOriginsRef.current[data.requestId]

      // SECURITY: Reject responses for unknown request ids
      if (expectedOrigin === undefined) {
        console.warn(
          '[DappWebView] Response dropped: no recorded origin for requestId',
          data.requestId,
          '- possible navigation race, duplicate response, or spoofing attempt.'
        )
        return
      }
      delete requestOriginsRef.current[data.requestId]

      const replyMessage = {
        topic: data.topic ? data.topic.replace('>', '<') : '< ambireProviderRequest',
        payload: { response: data.result, error: data.error },
        id: data.requestId
      }

      // SECURITY: Strict origin check in the injected JS. location.origin is read-only
      // and cannot be spoofed by the page. If the WebView navigated away during the
      // async user-confirmation, the response is silently dropped (not delivered to
      // the new origin).
      // SECURITY: Use __ambireNative.postMessage (captured before page JS ran)
      // instead of window.postMessage which a malicious site could have overwritten
      // to intercept response data.
      webviewRef.current?.injectJavaScript(`
         (function() {
           var expected = ${JSON.stringify(expectedOrigin)};
           if (!expected || location.origin !== expected) {
             return;
           }
           var postMessage = (window.__ambireNative && window.__ambireNative.postMessage) || window.postMessage.bind(window);
           postMessage(${JSON.stringify(replyMessage)}, location.origin);
         })();
         true;
       `)
    }
    eventBus.addEventListener('action.sendToDappWebView', onProviderResponse)
    return () => eventBus.removeEventListener('action.sendToDappWebView', onProviderResponse)
  }, [])

  useEffect(() => {
    const onBroadcastDappEvent = (data: any) => {
      const { event, data: eventData, origin: targetOrigin } = data

      // SECURITY: Each broadcast is bound to a specific dapp session origin
      // (propagated from Session.sendMessage -> mobileMessenger). If the WebView
      // has navigated to a different origin, drop the broadcast to prevent leaking
      // sensitive data (accountsChanged, chainChanged) to a malicious page.
      // If targetOrigin is missing (legacy callers), fall back to the WebView's
      // current URL origin - still better than no check at all.
      let expectedOrigin = targetOrigin
      if (!expectedOrigin) {
        try {
          expectedOrigin = new URL(currentUrlRef.current).origin
        } catch {
          console.warn('[DappWebView] Broadcast dropped: no origin available')
          return
        }
      }

      // SECURITY: __ambire_handleEvent is a custom global but console.warn is
      // overwritable; removed it from the injection path. The handler itself is
      // defined by our injected provider, so it is trustworthy if present.
      webviewRef.current?.injectJavaScript(`
        (function() {
          var expected = ${JSON.stringify(expectedOrigin)};
          if (!expected || location.origin !== expected) {
            return;
          }
          if (typeof window.__ambire_handleEvent === 'function') {
            window.__ambire_handleEvent(${JSON.stringify(event)}, ${JSON.stringify(eventData ?? null)});
          }
        })();
        true;
      `)
    }
    eventBus.addEventListener('action.broadcastDappEvent', onBroadcastDappEvent)
    return () => eventBus.removeEventListener('action.broadcastDappEvent', onBroadcastDappEvent)
  }, [])

  // After any bottom sheet that overlays the dapp WebView closes, synthesize
  // a `focus` event into the WebView. On the extension a tab loses/regains
  // OS-level focus around the wallet popup, which fires `window.focus` and
  // lets libraries like React Query (`refetchOnWindowFocus`) re-evaluate
  // stale queries — that is how chainlist's `useAccount` ends up calling
  // `net_version` and flipping the UI to "connected". On mobile the bottom
  // sheet is rendered inside the same RN screen above the WebView, so the
  // page never loses/regains focus and those queries never refire.
  // Dispatching a synthetic focus event after the sheet closes restores
  // parity with the extension behaviour.
  const dispatchWebViewFocus = useCallback(() => {
    // SECURITY: Use __ambireNative.dispatchEvent (captured before page JS ran)
    // so an overwritten window.dispatchEvent cannot intercept the focus event.
    webviewRef.current?.injectJavaScript(`
      (function() {
        try {
          var dispatch = (window.__ambireNative && window.__ambireNative.dispatchEvent) || window.dispatchEvent.bind(window);
          dispatch(new Event('focus'));
        } catch (e) {}
      })();
      true;
    `)
  }, [])

  // Listen for global bottom sheet close event to dispatch focus
  useEffect(() => {
    eventBus.addEventListener('requestsBottomSheet.closed', dispatchWebViewFocus)
    return () => eventBus.removeEventListener('requestsBottomSheet.closed', dispatchWebViewFocus)
  }, [dispatchWebViewFocus])

  const handleOpenPendingRequests = useCallback(() => {
    dispatch({
      type: 'method',
      params: {
        ctrlName: 'RequestsController',
        method: 'setCurrentUserRequestByIndex',
        args: [visibleUserRequests.length - 1]
      }
    })
  }, [dispatch, visibleUserRequests.length])

  //   - onLoadStart only resets state on real top-level navigations. On iOS
  //     every `onLoadStart` is treated as such; on Android only when the
  //     event is an explicit reload, there is no previously resolved URL,
  //     or the origin changed. This avoids resetting the bar for the noisy
  //     same-origin `onLoadStart` events that Android fires for SPA/hash
  //     routing (which was what made the bar stick / re-appear on heavy
  //     pages like Next.js apps).
  //   - onLoadProgress writes the raw progress value and keeps `isLoading`
  //     true while the page is still loading. It also doubles as the "done"
  //     signal on BOTH platforms: when `progress >= 1` it dismisses the bar.
  //     On Android `onLoadEnd(loading=false)` is unreliable for SPAs with
  //     persistent subresources; on iOS `onLoadEnd` and `onLoadProgress(1)`
  //     fire in non-deterministic order during BFCache (back/forward) restore
  //     so neither alone is sufficient. Monotonicity is enforced at the
  //     render layer inside `DappProgressBar`.
  //   - onLoadEnd only finishes when `event.nativeEvent.loading` is false
  //     (the "really done" signal) and caches the resolved URL. It serves as
  //     a backstop in case `onLoadProgress` never reaches 1.
  //   - onError dismisses the bar so failed pages don't leave it hanging.
  const handleLoadStart = useCallback(
    (event: { nativeEvent: { url: string; isReload?: boolean } }) => {
      // SECURITY: do NOT touch `currentUrlRef` here. `onLoadStart` fires at
      // navigation START (pre-commit). A page that calls `window.stop()`
      // after triggering a cross-origin navigation would otherwise leave
      // the trusted origin ref pointing at the destination URL while the
      // WebView is still rendering the old (phishing) page. The trusted
      // ref is only mutated post-commit - see `handleLoadProgress` (fast
      // path, first non-zero progress) and `handleNavigationStateChange`
      // (backstop, `loading=false`).

      let treatAsReload: boolean
      if (Platform.OS === 'ios') {
        treatAsReload = true
      } else if (event.nativeEvent.isReload) {
        treatAsReload = true
      } else if (!resolvedUrlRef.current) {
        treatAsReload = true
      } else {
        try {
          treatAsReload =
            new URL(event.nativeEvent.url).origin !== new URL(resolvedUrlRef.current).origin
        } catch {
          treatAsReload = true
        }
      }

      if (treatAsReload) {
        updateProgressState({ progress: 0, isLoading: true })
      }
    },
    [updateProgressState]
  )

  const handleLoadProgress = useCallback(
    (event: { nativeEvent: { progress: number; url?: string } }) => {
      const { progress, url } = event.nativeEvent

      // SECURITY + UX: post-commit fast path. WKWebView's `estimatedProgress`
      // and Android's `WebChromeClient.onProgressChanged` only emit non-zero
      // values once the response has been received and the new document is
      // being parsed - i.e. AFTER `didCommitNavigation:` / `onPageStarted`
      // commits. By that point a `window.stop()` from JS can no longer
      // revert the URL: commit IS the security boundary, the same one real
      // browsers use for their address bar. Updating here gives a URL-bar
      // refresh ~1-2s earlier than the `loading=false` backstop in
      // `handleNavigationStateChange`, while preserving the spoof guarantee.
      if (progress > 0 && url) {
        try {
          if (new URL(url).protocol === 'https:') {
            updateCurrentOriginRef(url)
            setCurrentUrl(url)
            setDappUrl?.(url)
          }
        } catch {
          // ignore unparseable URLs
        }
      }

      if (progress >= 1) {
        if (url) resolvedUrlRef.current = url
        updateProgressState({ progress: 1, isLoading: false })
        return
      }
      updateProgressState({ progress, isLoading: true })
    },
    [updateProgressState, updateCurrentOriginRef, setDappUrl]
  )

  const handleLoadEnd = useCallback(
    (event: { nativeEvent: { url: string; loading: boolean } }) => {
      if (event.nativeEvent.loading) return
      resolvedUrlRef.current = event.nativeEvent.url
      updateProgressState({ progress: 1, isLoading: false })
    },
    [updateProgressState]
  )

  const handleLoadError = useCallback(() => {
    updateProgressState({ progress: 0, isLoading: false })
  }, [updateProgressState])

  const handleRenderProcessGone = useCallback(
    // Typed as `any` because Android's `onRenderProcessGone` yields a
    // `WebViewRenderProcessGoneEvent` while iOS's `onContentProcessDidTerminate`
    // yields a `WebViewTerminatedEvent`, and we wire the same callback to both.
    (syntheticEvent: any) => {
      const nativeEvent = syntheticEvent?.nativeEvent
      console.warn('[DappWebView] WebView process terminated, reloading dapp...', nativeEvent)
      updateProgressState({ progress: 0, isLoading: false })
      requestOriginsRef.current = {}
      webviewRef.current?.reload()
    },
    [updateProgressState]
  )

  return (
    <MobileLayoutContainer
      keyboardAwareFooter={false}
      footerStyle={{ ...spacings.ph0, ...spacings.pt0 }}
      footer={
        <>
          {isLoading && <DappProgressBar progress={progress} />}
          <DappWebViewFooter
            headerControl={headerControl}
            handleOpenSearchModal={handleOpenSearchModal}
            handleGoBack={handleGoBack}
            canGoBack={canGoBack}
            handleRefresh={handleRefresh}
            account={account}
            currentDapp={currentDapp}
            smartAccountType={smartAccountType}
            onManageAppClosed={dispatchWebViewFocus}
            showBackButton={showBackButton}
          />
        </>
      }
    >
      {!!visibleUserRequests.length && !currentUserRequest && (
        <View style={spacings.phSm}>
          <Banner
            type="info"
            singleRow
            title={`You have ${visibleUserRequests.length} pending ${
              visibleUserRequests.length === 1 ? 'request' : 'requests'
            }.`}
            CustomIcon={() => (
              <AmbireLogoWithBackgroundAndLogotype
                withText={false}
                style={spacings.mrTy}
                width={30}
                height={30}
              />
            )}
            buttonText="Open"
            onPress={handleOpenPendingRequests}
          />
        </View>
      )}
      <View style={flexbox.flex1}>
        <WebView
          ref={webviewRef}
          source={{ uri: sourceUri }}
          userAgent={DESKTOP_USER_AGENT}
          onNavigationStateChange={handleNavigationStateChange}
          injectedJavaScriptBeforeContentLoaded={injectionScript}
          onMessage={handleMessage}
          javaScriptEnabled={true}
          domStorageEnabled={true}
          allowFileAccessFromFileURLs={false}
          allowUniversalAccessFromFileURLs={false}
          originWhitelist={['https://*', 'blob:*']}
          setSupportMultipleWindows={false}
          onShouldStartLoadWithRequest={handleShouldStartLoadWithRequest}
          onLoadStart={handleLoadStart}
          onLoadEnd={handleLoadEnd}
          onLoadProgress={handleLoadProgress}
          onError={handleLoadError}
          onRenderProcessGone={handleRenderProcessGone}
          onContentProcessDidTerminate={handleRenderProcessGone}
          webviewDebuggingEnabled={__DEV__}
          nestedScrollEnabled={true}
        />
      </View>

      <BottomSheet
        id="dapp-webview-search"
        sheetRef={searchModalRef}
        adjustToContentHeight={false}
        closeBottomSheet={closeSearchModal}
        onClosed={dispatchWebViewFocus}
        HeaderComponent={searchHeaderComponent}
        flatListProps={searchFlatListProps}
      />
    </MobileLayoutContainer>
  )
}

export default DappWebViewScreen
