import { buildSelector } from '@helpers/buildSelector'

// TODO: this should be refactored; we should have single file with selector IDs
const selectors = {
  getStarted: {
    createNewAccountButton: 'create-new-account-btn',
    createRecoveryPhraseButton: 'review-seed-phrase-btn',
    importAccountButton: 'button-import-account',
    confirmationMessageForViewOnly: 'added-successfully-text',
    confirmationMessageAmbireWallet: 'wallet-ready-to-use-text',
    savedPhraseButton: 'create-seed-phrase-write-continue-btn',
    recoveryPhraseHeader: 'back-up-recovery-phrase-text',
    copyRecoveryPhraseButton: 'copy-recovery-phrase',
    recoveryPhraseCopiedSnackbar: 'success-0', // first snackbar that appears has value 0 after dash
    checkbox: 'checkbox',
    enterPassField: 'enter-pass-field',
    repeatPassField: 'repeat-pass-field',
    createKeystorePassBtn: 'create-keystore-pass-btn',
    watchAddress: 'watch-an-address-button',
    addMoreAccountsButton: 'add-more-accounts-btn',
    addOneMoreAddress: 'add-one-more-address',
    importExistingAccBtn: 'import-existing-account-btn',
    importMethodPrivateBtn: 'import-method-private-key',
    importMethodRecoveryPhrase: 'import-method-recovery-phrase',
    importMethodJSON: 'import-method-json-backup-file',
    enterSeedPhraseField: 'enter-seed-phrase-field',
    enterPrivateKeyField: 'enter-private-key-field',
    advancedPassPhraseSwitch: 'enable-passphrase-toggle',
    recoveryPhrasePassphraseField: 'input-passphrase',
    warningCheckbox: 'backup-warning-checkbox',
    addressEnsField: 'address-ens-field',
    showMoreBtn: 'show-more-btn',
    viewOnlyBtnImport: 'view-only-button-import',
    importBtn: 'import-button',
    openDashboardButton: 'onboarding-completed-open-dashboard-btn',
    editFirstAccNameButton: 'edit-btn-for-edit-name-field-0', // same id used for clearing input field; after edit for checking confirmation pill 'Save'
    editAccountNameInputField: 'edit-name-field-0',
    saveAndContinueBtn: 'button-save-and-continue',
    hdPathLegerLive: 'hd-path-option-ledger-live',
    changeHDPathButton: 'change-hd-path-btn',
    hdPathConfirmButton: 'hd-path-confirm-btn',
    hdPathLegerLegacy: 'hd-path-option-ledger-legacy',
    smartAccountPicker: 'add-account-' // need add index 5
  },
  dashboard: {
    dashboardGasTankBalance: 'dashboard-gas-tank-balance',
    appsButton: 'dashboard-button-explore',
    tokensTabButton: 'tokens-defi',
    noTokensText: 'no-tokens-text',
    tokenTitleText: '[data-testid^="token-balance-"]',
    nftTabButton: 'tab-nft',
    noCollectiblesText: 'no-collectibles-text',
    defiTabButton: 'tab-defi',
    noProtocolsText: 'no-protocols-text',
    suggestProtocolText: 'suggest-protocol-text',
    openTicketLink: 'open-ticket-link',
    activityTabButton: 'tab-activity',
    viewTransactionLink: 'view-transaction-link',
    sendButton: 'dashboard-button-send',
    swapAndBridgeButton: 'dashboard-button-swap-and-bridge',
    hamburgerButton: 'dashboard-hamburger-btn',
    balanceErrorIcon: 'balance-affecting-error-icon',
    portfolioErrorAlert: 'portfolio-error-alert',
    noTransactionOnActivityTab: 'no-transaction-history-text',
    transactionSendText: '(//div[contains(text(),"Send")])[2]', // TODO: change once we have id on FE
    transactionFuelGasTankText: '(//div[contains(text(),"Fuel gas tank")])',
    swapAndBridgeTransactionText: '//div[contains(text(),"Swap/Bridge")]', // TODO: change once we have id on FE
    activityTabConfirmedPill: '//div[contains(text(),"Confirmed")]',
    confirmedTransactionPill: '(//div[contains(text(),"Confirmed")])[2]', // TODO: chage once we have id on FE
    activityTransactionConfirmed: 'activity-confirmed-step',
    fuelGasTankTransactionPill: '//div[contains(text(),"Fuel gas tank with")]', // TODO: chage once we have id on FE,
    grantApprovalText: '//div[contains(text(),"Approve")]', // TODO: change once we have id on FE,
    magnifyingGlassIcon: 'search-glass-icon',
    tokensNetworksDropdownButton: 'networks-dropdown-tokens',
    nftNetworkDropdownButton: 'networks-dropdown-collectibles',
    defiNetworkDropdownButton: 'networks-dropdown-defi',
    activityNetworkDropdownButton: 'networks-dropdown-activity',
    tokenBalance: '[data-testid^="token-balance"]',
    networkBase: '//div[text()="Base"]',
    nftTitle: 'collection-item',
    nftsTitle: '[data-testid^="collection-item"]',
    hideTokenButton: 'hide-token-button',
    yesHideItButton: 'yes-hide-it-text',
    hideTokenModalTitle: 'hide-token-modal-title',
    hideTokenModalDescription: 'hide-token-modal-description',
    rewardsButton: 'dashboard-button-rewards',
    rewardsForClaimingButton: 'marketing-banner-button',
    rewardsLink: '//div[contains(text(),"Ambire Rewards")]',
    projectedRewardsClaimButton: 'projected-rewards-claim-button',
    searchInputPlaceholder: 'search-input-placeholder',
    searchInputField: 'search-input-field'
  },
  settings: {
    navAccounts: 'settings-nav-accounts',
    navRecoveryPhrases: 'settings-nav-recovery-phrases',
    createNewRecoveryPhraseButton: 'create-new-recovery-phrase',
    importAccountButton: 'import-account',
    connectHardwareWallet: 'connect-hardware-wallet',
    watchAnAddressButton: 'watch-an-address-button',
    viewOnlyAddressField: 'address-ens-field',
    viewOnlyImportButton: 'view-only-button-import',
    validENSDomainText: '//div[contains(text(),"Valid ENS domain")]',
    addedSuccessfullyText: '//div[contains(text(),"Added successfully")]',
    accessAccFromDashboardInfoText: '//div[contains(text(),"access your accounts")]',
    addAccountButton: 'add-account-modal',
    hiddenTokenName: 'hidden-token-name', // works for custom tokens section
    hiddenTokenNetwork: 'hidden-token-network', // works for custom tokens section
    unhideTokenButton: 'unhide-button',
    youDontHaveInfoText: 'you-dont-have-any-text', // there can be multiple on same page,
    manageAccountTreeDotsButton: 'account', // on accounts page, has multiple sam IDs,
    removeAccountButton: '//div[contains(text(),"Remove account")]',
    confirmRemoveAccountButton: 'confirm-remove-account-button',
    customTokens: {
      addCustomTokenButton: 'add-custom-token-button',
      addTokenModalTitle: 'add-token-modal-title-text',
      ethNetworkOption: 'option-Ethereum',
      opMainnetNetworkOption: 'option-OP-Mainnet',
      bnbNetworkOption: 'option-BNB-Chain',
      polygonNetworkOption: 'option-Polygon',
      mantleNetworkOption: 'option-Mantle',
      baseNetworkOption: 'option-Base',
      arbitrumNetworkOption: 'option-Arbitrum',
      tokenAddressField: 'token-address-field',
      customNameTokenText: 'custom-token-name', // visible after entering valid address
      confirmedPillText: 'confirmed-pill-text',
      addTokenButton: 'add-token-button',
      addedTokenSnackbar: '//span[contains(text(),"Added token")]',
      tokenRemovedSnackbar: '//span[contains(text(),"Token removed")]',
      removeCustomTokenButton: 'remove-button'
    }
  },
  transaction: {
    feeTokensSelectDropdown: 'fee-option-select',
    feeSpeedSelectDropdown: 'fee-speed-select',
    feeSpeedSlow: 'option-slow',
    feeSpeedMedium: 'option-medium',
    feeSpeedFast: 'option-fast',
    feeSpeedApe: 'option-ape',
    feeTokenInDollars: '//div[contains(text(), "<$") or contains(text(), "$")]',
    confirmingYourTransactionText: 'confirming-your',
    explorer: {
      txnSignedStep: 'signed-step',
      txnProgressStep: 'txn-progress-step',
      txnConfirmedStep: 'finalized-rows',
      recepientAddressBlock: 'recipient-address-undefined'
    },
    backButton: 'back-button',
    amountField: 'amount-field',
    proceedBtn: 'proceed-btn',
    transactionError: '//span[contains(text(),"Error")]', // e.g. snackbar when relayer is down,
    dualChoiceModalAcceptButton: 'dual-choice-modal-primary-button',
    dualChoiceModalTitle: 'dual-choice-modal-title-text',
    previousFeeAmountText: 'previous-fee-amount',
    updatedFeeAmountText: 'updated-fee-amount'
  },
  // TODO: update selectors wiyh testID
  ambireRewards: {
    connectAmbireButton: '//button[contains(text(),"Connect Ambire")]',
    claimRewardButton: '//button[contains(text(),"Claim")]',
    readAnnouncementHyperlink: '//a[contains(@href, "rewards-enters")]',
    faqFirstQuestion: '//span[contains(text(),"What is Ambire")]',
    faqFirstAnswer: '(//div/p)[2]',
    faqSecondQuestion: '//span[contains(text(),"Is Ambire")]',
    faqSecondAnswer: '(//div/p)[3]',
    faqThirdQuestion: '//span[contains(text(),"Can I participate with a wallet")]',
    faqThirdAnswer: '(//div/p)[4]',
    faqFourthQuestion: '//span[contains(text(),"Which tokens")]',
    faqFourthAnswer: '(//div/p)[5]',
    faqFifthQuestion: '//span[contains(text(),"How is Swap&Bridge")]',
    faqFifthAnswer: '(//div/p)[6]',
    faqSixthQuestion: '//span[contains(text(),"Can I use my")]',
    faqSixthAnswer: '(//div/p)[7]',
    faqSeventhQuestion: '//span[contains(text(),"Can I participate with multiple")]',
    faqSeventhAnswer: '(//div/p)[8]',
    faqEightQuestion: '//span[contains(text(),"How long is the current")]',
    faqEightAnswer: '(//div/p)[9]',
    faqNinthQuestion: '//span[contains(text(),"What are projected")]',
    faqNinthAnswer: '(//div/p)[10]',
    pageTitle: '//h1',
    pageDescription: '//p',
    homePage: '//span[contains(text(),"Home")]',
    leaderboardPage: '//span[contains(text(),"Rewards")]',
    rewardsPoolPage: '//span[contains(text(),"Rewards Pool")]',
    walletPage: '//span[contains(text(),"$Wallet")]',
    faqPage: '//span[contains(text(),"FAQ")]'
  },
  sigtool: {
    connectWalletButton: '.button-connect',
    metamaskOption: 'div[class*="wallet-button-container"] >> text=MetaMask',
    connectionSuccessfulText: '//div[contains(text(),"Connection Successful")]',
    humanMessageTextbox: '.messageInputHeader',
    signButton: '.actionContainer > button > span',
    messageSignatureTitle: '.signatureResult-title',
    autoLoginSwitch: 'label > input[type="checkbox"] ~ div',
    signRequestForEVMText: '//div[contains(text(), "SigTool for EVM")]',
    deceptiveAppError: '//span[contains(text(),"Deceptive")]',
    deceptiveAppErrorDescription: '//div[contains(text(),"The app")]',
    signInSiweButton: '//div[contains(text(),"Sign in")]',
    error: '#error',
    dappWrapper: 'dapp-wrapper',
    sigToolIconButton: 'manage-dapp-dropdown',
    sigToolNetworkEth: '//div[contains(text(), "Ethereum")]',
    sigToolNetworkBase: '//div[contains(text(), "Base")]',
    disconnectButton: '//button[contains(text(), "Disconnect Wallet")]',
    disconnectDapp: '//div[contains(text(), "Disconnect")]'
  },
  swapAndBridge: {
    fromTokenDropdown: 'from-token-select',
    receiveTokenDropdown: 'to-token-select',
    receiveNetworkDropdown: 'to-network-select',
    oneInchSwapRoute: '//div[contains(text(), "1Inch")]',
    kyberSwapRoute: '//div[contains(text(), "Kyberswap")]',
    sushiSwapRoute: 'div:has-text("SushiSwap Aggregator")' // no route
  },
  searchInput: 'search-input',
  backArrowButton: 'back-arrow-button',
  account: 'account',
  importMethodTrezor: 'import-method-trezor',
  trezorConnectConfirmTerms: '@analytics/continue-button',
  buttonProceedSeedPhrase: 'button-proceed-seed-phrase',
  doNotSaveSeedBtn: 'do-not-save-seed-button',
  saveAsDefaultSeedBtn: 'save-seed-button',
  getStartedBtnImport: 'get-started-button-import',
  keystoreBtnCreate: 'keystore-button-create',
  keystoreBtnContinue: 'keystore-button-continue',
  editBtnForEditNameField: 'edit-btn-for-edit-name-field',
  editFieldNameField: 'edit-name-field',
  getStartedBtnAdd: 'get-started-button-add',
  addToAddressBookButton: 'add-to-address-book-button',
  addContactFormButton: 'add-contact-form-modal',
  contactNameField: 'contact-name-field',
  contactNameText: 'contact-name-text', // TODO: selector could be more precise
  contactAddressText: 'address',
  sendFormAddToAddresBook: 'send-form-add-to-address-book-button',
  formAddContactNameField: 'form-contact-name-field',
  formAddToContactsButton: 'form-add-to-contacts-button',
  buttonAddAccount: 'button-add-account',
  checkbox: 'checkbox',
  addAccount: 'add-account',
  seedPhraseInputFieldDynamic: 'seed-phrase-field',
  getStartedCreateHotWallet: 'get-started-create-hot-wallet',
  setUpWithSeedPhraseBtn: 'set-up-with-seed-phrase-btn',
  createSeedPrepareCheckboxDyn: 'create-seed-prepare-checkbox',
  reviewSeedPhraseBtn: 'review-seed-phrase-btn',
  recoveryWithSeedWordDyn: 'recovery-with-seed-word',
  createSeedPhraseWriteContinueBtn: 'create-seed-phrase-write-continue-btn',
  seedWordNumberToBeEntered: 'seed-word-number-to-be-entered',
  seedWordPositionFieldDyn: 'seed-word-position-field',
  createSeedPhraseConfirmContinueBtn: 'create-seed-phrase-confirm-continue-btn',
  personalizeAccount: 'personalize-account',
  pinExtensionCloseBtn: 'pin-extension-close-btn',
  accountSelectBtn: 'account-select-btn',
  selectSeedPhraseLength: 'select-seed-phrase-length',
  option24WordsSeedPhrase: 'option-i-have-24-word-phrase',
  selectChangeHdPath: 'select-change-hd-path',
  optionBip44LedgerLive: 'option-bip44-ledger-live',
  importExistingWallet: 'import-existing-wallet',
  optionLegacyLedgerMyEtherWalletMyCrypto: 'option-legacy-ledger-myetherwallet-mycrypto',
  getStartedButtonConnectHwWallet: 'get-started-button-connect-hw-wallet',
  selectHwOptionTrezor: 'select-hw-option-trezor',
  trezorPermissionConfirmButton: '@permissions/confirm-button',
  trezorExportAddressConfirmButton: '@export-address/confirm-button',
  enterCurrentPassField: 'enter-current-pass-field',
  enterNewPassField: 'enter-new-pass-field',
  repeatNewPassField: 'repeat-new-pass-field',
  changeDevicePassButton: 'change-device-pass-button',
  bottomSheet: 'bottom-sheet',
  devicePassSuccessModal: 'device-pass-success-modal',
  lockExtensionButton: 'lock-extension-button',
  passphraseField: 'passphrase-field',
  buttonUnlock: 'button-unlock',
  buttonUnlockBiometricsIcon: 'button-unlock-biometrics-icon',
  fullBalance: 'full-balance',
  tabNft: 'tab-nft',
  collectionItem: 'collection-item',
  collectiblePicture: 'collectible-picture',
  collectibleRow: 'collectible-row',
  addressBookMyWalletContactDyn: 'address-book-my-wallet-contact',
  continueAnywayCheckboxSaB: 'checkbox',
  continueAnywayButton: '//div[contains(text(),"Continue anyway")]',
  transferButtonConfirm: 'transfer-button-confirm',
  addAccountField: 'add-account-field',
  importExistingSeedBtn: 'import-existing-seed-btn',
  createSeedBtn: 'create-seed-btn',
  importFromSavedSeed: 'import-from-saved-seed',
  nativeTokenPolygonDyn: 'token-0x0000000000000000000000000000000000000000-polygon',
  tokenSend: 'token-send',
  tokensSelect: 'tokens-select',
  queueAndSignLaterButton: 'queue-and-sign-later-button',
  deleteTxnCallDyn: 'delete-txn-call',
  feeSlow: 'option-slow',
  feeMedium: 'option-medium',
  feeFast: 'option-fast',
  feeApe: 'option-ape',
  transactionButtonReject: 'transaction-button-reject',
  totalPortfolioAmountInteger: 'total-portfolio-amount-integer',
  privateKeyWarningCheckbox1: 'private-key-warning-checkbox-1',
  privateKeyWarningCheckbox2: 'private-key-warning-checkbox-2',
  nativeTokenBaseDashboard: 'token-0x0000000000000000000000000000000000000000-8453',
  bannerButtonOpen: 'dashboard-info-banner',
  bannerButtonReject: 'banner-button-reject',
  confettiModalActionButton: 'confetti-modal-action-button',
  refreshButton: 'refresh-button',
  dashboardGasTankBalance: 'dashboard-gas-tank-balance',
  createSmartAccountGasTankModalButton: 'create-smart-account-gas-tank-modal-button',
  confirmFollowUpTxn: 'confirm-follow-up-txns-checkbox',
  USDC: 'option-0x0b2c639c533813f4aa9d7837caf62653d097ff85.usdc',
  signTransactionButton: 'transaction-button-sign',
  maxAvailableAmount: 'max-available-amount',
  // Swap & Bridge selectors
  selectRouteButton: 'select-route',
  routeLoadingTextSab: 'route-loading-text-sab',
  fromAmountInputSab: 'from-amount-input-sab',
  switchTokensTooltipSab: 'switch-tokens-condition-tooltip-sab',
  switchCurrencySab: 'switch-currency-sab',
  routePrioritySab: 'route-priority-sab',
  highPriceImpactSab: '//div[contains(text(), "Very high price impact")]', // TODO: change with ID when we add it
  highSlippageModal: '//div[contains(text(), "higher slippage")]', // TODO: change with ID when we add it
  settingsAddNetworkManually: 'add-network-manually',
  settingsAddNetworkFromChainlist: 'add-network-from-chainlist',
  removeNetworkButton: 'remove-network-btn',
  removeNetworkConfirmButton: 'remove-network-confirm-btn',
  signButton: 'sign-button',
  backButton: 'back-button',
  submitButton: 'button-submit',
  txnStatus: 'txn-status',
  batchModalGotIt: 'queue-modal-got-it-button',
  signButtonSwap: 'swap-button-sign',
  addMoreButton: 'add-more-button',
  flipIcon: 'flip-icon',
  swapSignButton: 'swap-button-sign',
  addToBatchButton: 'batch-btn',
  goDashboardButton: 'go-dashboard-button',
  txnConfirmed: 'txn-confirmed',
  maxAmountButton: 'max-amount-button',
  transactionConfirmedText: 'transaction-confirmed-text',
  closeTransactionProgressPopUpButton: '//div[contains(text(),"Close")]',
  // Top up
  modalGasTankBalance: 'gas-tank-balance',
  topUpButton: 'top-up-gas-tank-modal-button',
  closeProgressModalButton: 'track-progress-primary-button',
  // Network Management
  // TODO: change once we have IDs on FE
  disableNetworkButton: 'disable-network-btn',
  disableNetworkConfirmButton: 'disable-network-confirm-btn',
  // (kohaku) RPC provider options in the edit-network modal
  rpcProviderOptionRpc: 'rpc-provider-option-rpc',
  rpcProviderOptionHelios: 'rpc-provider-option-helios',
  rpcProviderOptionColibri: 'rpc-provider-option-colibri',
  addRPCURLButton: '//div[.//div[text()="Add RPC URL"]]//div[text()="Add"]',
  addNetworkButton: '//div[.//div[text()="Network details"]]//div[text()="Add network"]',
  connectWalletButton:
    "//div[.//span[text()='Include Testnets']]//button[normalize-space()='Connect Wallet']",
  chainlistSearchPlaceholder: 'input[placeholder*="ETH"]',
  addToMetamaskButton: '//button[contains(text(),"Add to Metamask")]',
  confirmaddNetworkOnChainlistButton: '//div[contains(text(),"Enable network")]',
  blockExplorerURL: (url: string) => `//div[contains(text(),"${url}")]`,
  networkDetailEditButton: '//div[.//div[text()="Network details"]]//div[text()="Edit"]',
  // edit network modal
  editNetworkModalTitle: '//div[text()="Edit network"]',
  editNetworkCancelButton: '//div[contains(text(),"Cancel")]',
  editNetworkSaveButton: '//div[contains(text(),"Save")]',
  networkSettingsSavedSnackbar: (networkName: string) =>
    `((//div[contains(normalize-space(), "${networkName} settings saved!")]))[4]`, // TODO: snackbar selector finding 8 elements; change once we have ID on FE
  // Sign
  dappConnectButton: 'dapp-connect-button',
  dappSecurityCheckPassed: 'dapp-security-check-passed',
  signMessageButton: 'button-sign',
  // Notifications
  networkSuccessfullyAddedSnackbar:
    '(//div[contains(normalize-space(), "Network successfully added!")])[4]', // TODO: snackbar selector finding 8 elements; change once we have ID on FE
  contactSuccessfullyAddedSnackbar:
    '(//div[contains(normalize-space(), "Contact added to Address Book")])[4]', // TODO: snackbar selector finding 8 elements; change once we have ID on FE
  importMethodLedger: 'import-method-ledger',
  keystoreMigration: {
    recoveryPhraseRow: (id: string) => `recovery-phrase-row-${id}`,
    manageRecoveryPhrase: (id: string) => `manage-recovery-phrase-${id}`,
    recoveryPhraseValue: 'recovery-phrase-value',
    recoveryPhrasePassphraseValue: 'recovery-phrase-passphrase-value',
    revealRecoveryPhraseButton: 'reveal-recovery-phrase-button',
    copyRecoveryPhraseButton: 'copy-recovery-phrase-button',
    exportKeyButton: (addr: string) => `export-key-button-${addr}`,
    privateKeyValue: 'private-key-value',
    revealPrivateKeyButton: 'reveal-private-key-button',
    copyPrivateKeyButton: 'copy-private-key-button'
  }
}

type SelectorKey = keyof typeof selectors
type Selectors = { [K in SelectorKey]?: string }

export const SELECTORS: Selectors = Object.fromEntries(
  Object.entries(selectors).map(([key, value]) => [key, buildSelector(value)])
)

export default selectors
